feat: option to define available options for user (#264)
* fix: add i18n

* feat: option to show selected options to user

* fix: add ts types

* test: setup new test

* test: add test for option menu

* test: add test for option menu

* fix: add `onAvailableOptionsChanged` to exceluploaddialog

* test: fix upload artifact

* test: fix upload artifact

* test: fix op5 test

* test: log

* test: log

* test: fix test

* test: fix test

* fix: update version

* test: fix test

* test: fix test

* test: fix test

* test: fix test

* test: fix test

* test: fix test

* test: fix test

* test: fix test

* test: fix test

* test: fix test

* test: fix test

* test: pnpm install

* test: remove pupeteer

* test: fix

* test: fix test

* test: fix test

* test: fix test

* test: fix test

* test: fix test

* test: fix test

* test: fix test

diff --git a/.github/workflows/opa5-test.yml b/.github/workflows/opa5-test.yml
--- a/.github/workflows/opa5-test.yml
+++ b/.github/workflows/opa5-test.yml
@@ -32,16 +32,18 @@ jobs:
 
       - name: checkout excelUpload Repo
         uses: actions/checkout@v3
+        with:
+          ref: ${{ github.head_ref }}
 
       - name: use pnpm
         uses: pnpm/action-setup@v2
         with:
-          version: 7.17.1
+          version: 8.6.0
 
       - name: use node 16
         uses: actions/setup-node@v3
         with:
-          node-version: 16
+          node-version: 18
           cache: "pnpm"
 
       # we need this for workspace mgmt
@@ -70,13 +72,6 @@ jobs:
       - name: copy test apps
         run: npm run copyTestApps
 
-      - name: pnpm install for test apps
-        run: |
-          pnpm install --no-frozen-lockfile
-
-      - name: Run Build
-        run: npm run build
-
       # update chromedriver
       - name: update chromedriver to latest
         run: |
@@ -85,6 +80,18 @@ jobs:
       - name: install @sap/cds-dk
         run: |
           npm i -g @sap/cds-dk
+      
+      - name: install ui5-test-runner
+        run: |
+          npm i -g ui5-test-runner
+
+      - name: pnpm install
+        run: |
+          npm pkg delete scripts.prepare
+          pnpm install --no-frozen-lockfile
+      
+      - name: Run Build
+        run: npm run build
 
       # run app
       - name: start cap server
@@ -97,13 +104,20 @@ jobs:
 
       # run opa5 tests
       - name: test opa5 ${{ matrix.scenario }} ui5 ${{ matrix.ui5version }}
+        id: opa5test  # An ID for the step to refer to its outputs later
+        continue-on-error: true  # The job will not stop if this step fails
         run: |
           while ! nc -z localhost 4004; do sleep 0.1; done
           while ! nc -z localhost ${{ env.TESTAPPPORT }}; do sleep 0.1; done
-          pnpm --filter ui5-cc-excelupload-sample ui5-test-runner --url http://localhost:${{ env.TESTAPPPORT }}/test/integration/opaTests.qunit.html --screenshot false
+          ui5-test-runner --url http://localhost:${{ env.TESTAPPPORT }}/test/integration/opaTests.qunit.html --screenshot false
 
       - name: upload artifact of report folder
         uses: actions/upload-artifact@v3
         with:
           name: ui5testrunner-report-${{ matrix.scenario }}-${{ matrix.ui5version }}
-          path: ./examples/report
+          path: ./report
+      
+      # Fail the job if the 'test opa5' step failed
+      - name: Check test status
+        if: steps.opa5test.outcome != 'success'
+        run: exit 1
