chore: update dependencies (#717)

diff --git a/.github/workflows/wdi5-test.yml b/.github/workflows/wdi5-test.yml
--- a/.github/workflows/wdi5-test.yml
+++ b/.github/workflows/wdi5-test.yml
@@ -96,7 +96,9 @@ jobs:
 
       # run wdi5 tests
       - name: test wdi5 ${{ matrix.scenario }} ui5 ${{ matrix.ui5version }}
+        id: wdi5_test
         if: matrix.scenario != 'ordersv4fecds'
+        continue-on-error: true
         run: |
           while ! nc -z localhost 4004; do sleep 0.1; done
           while ! nc -z localhost ${{ env.TESTAPPPORT }}; do sleep 0.1; done
@@ -121,3 +123,11 @@ jobs:
         with:
           name: timeline-report-${{ matrix.scenario }}-${{ matrix.ui5version }}
           path: ./examples/reports/timeline
+
+      # Optional: Fail the workflow if tests failed
+      - name: Check Test Results
+        if: always()
+        run: |
+          if [[ "${{ steps.wdi5_test.outcome }}" == "failure" ]]; then
+            exit 1
+          fi
